// Code generated from TypeScript enums. DO NOT EDIT.
package openmeteo

import "strconv"

type Unit byte

const (
	UnitUndefined Unit = iota
	UnitCelsius
	UnitCentimetre
	UnitCubicMetrePerCubicMetre
	UnitCubicMetrePerSecond
	UnitDegreeDirection
	UnitDimensionlessInteger
	UnitDimensionless
	UnitEuropeanAirQualityIndex
	UnitFahrenheit
	UnitFeet
	UnitFraction
	UnitGddCelsius
	UnitGeopotentialMetre
	UnitGrainsPerCubicMetre
	UnitGramPerKilogram
	UnitHectopascal
	UnitHours
	UnitInch
	UnitIso8601
	UnitJoulePerKilogram
	UnitKelvin
	UnitKilopascal
	UnitKilogramPerSquareMetre
	UnitKilometresPerHour
	UnitKnots
	UnitMegajoulePerSquareMetre
	UnitMetrePerSecondNotUnitConverted
	UnitMetrePerSecond
	UnitMetre
	UnitMicrogramsPerCubicMetre
	UnitMilesPerHour
	UnitMillimetre
	UnitPascal
	UnitPerSecond
	UnitPercentage
	UnitSeconds
	UnitUnixTime
	UnitUsAirQualityIndex
	UnitWattPerSquareMetre
	UnitWmoCode
	UnitPartsPerMillion
	UnitKilogramPerCubicMetre
)

var unitNames = [...]string{
	"undefined",
	"celsius",
	"centimetre",
	"cubic_metre_per_cubic_metre",
	"cubic_metre_per_second",
	"degree_direction",
	"dimensionless_integer",
	"dimensionless",
	"european_air_quality_index",
	"fahrenheit",
	"feet",
	"fraction",
	"gdd_celsius",
	"geopotential_metre",
	"grains_per_cubic_metre",
	"gram_per_kilogram",
	"hectopascal",
	"hours",
	"inch",
	"iso8601",
	"joule_per_kilogram",
	"kelvin",
	"kilopascal",
	"kilogram_per_square_metre",
	"kilometres_per_hour",
	"knots",
	"megajoule_per_square_metre",
	"metre_per_second_not_unit_converted",
	"metre_per_second",
	"metre",
	"micrograms_per_cubic_metre",
	"miles_per_hour",
	"millimetre",
	"pascal",
	"per_second",
	"percentage",
	"seconds",
	"unix_time",
	"us_air_quality_index",
	"watt_per_square_metre",
	"wmo_code",
	"parts_per_million",
	"kilogram_per_cubic_metre",
}

func (v Unit) String() string {
	if i := int(v); i >= 0 && i < len(unitNames) {
		return unitNames[i]
	}
	return "Unit(" + strconv.Itoa(int(v)) + ")"
}

type Model byte

const (
	ModelUndefined Model = iota
	ModelBestMatch
	ModelGfsSeamless
	ModelGfsGlobal
	ModelGfsHrrr
	ModelMeteofranceSeamless
	ModelMeteofranceArpegeSeamless
	ModelMeteofranceArpegeWorld
	ModelMeteofranceArpegeEurope
	ModelMeteofranceAromeSeamless
	ModelMeteofranceAromeFrance
	ModelMeteofranceAromeFranceHd
	ModelJmaSeamless
	ModelJmaMsm
	ModelJmsGsm
	ModelJmaGsm
	ModelGemSeamless
	ModelGemGlobal
	ModelGemRegional
	ModelGemHrdpsContinental
	ModelIconSeamless
	ModelIconGlobal
	ModelIconEu
	ModelIconD2
	ModelEcmwfIfs04
	ModelMetnoNordic
	ModelEra5Seamless
	ModelEra5
	ModelCerra
	ModelEra5Land
	ModelEcmwfIfs
	ModelGwam
	ModelEwam
	ModelGlofasSeamlessV3
	ModelGlofasForecastV3
	ModelGlofasConsolidatedV3
	ModelGlofasSeamlessV4
	ModelGlofasForecastV4
	ModelGlofasConsolidatedV4
	ModelGfs025
	ModelGfs05
	ModelCMCCCM2VHR4
	ModelFGOALSF3HHighresSST
	ModelFGOALSF3H
	ModelHiRAMSITHR
	ModelMRIAGCM32S
	ModelECEarth3PHR
	ModelMPIESM12XR
	ModelNICAM168S
	ModelCamsEurope
	ModelCamsGlobal
	ModelCfsv2
	ModelEra5Ocean
	ModelCmaGrapesGlobal
	ModelBomAccessGlobal
	ModelBomAccessGlobalEnsemble
	ModelArpaeCosmoSeamless
	ModelArpaeCosmo2i
	ModelArpaeCosmo2iRuc
	ModelArpaeCosmo5m
	ModelEcmwfIfs025
	ModelEcmwfAifs025
	ModelGfs013
	ModelGfsGraphcast025
	ModelEcmwfWam025
	ModelMeteofranceWave
	ModelMeteofranceCurrents
	ModelEcmwfWam025Ensemble
	ModelNcepGfswave025
	ModelNcepGefswave025
	ModelKnmiSeamless
	ModelKnmiHarmonieAromeEurope
	ModelKnmiHarmonieAromeNetherlands
	ModelDmiSeamless
	ModelDmiHarmonieAromeEurope
	ModelMetnoSeamless
	ModelEra5Ensemble
	ModelEcmwfIfsAnalysis
	ModelEcmwfIfsLongWindow
	ModelEcmwfIfsAnalysisLongWindow
	ModelUkmoGlobalDeterministic10km
	ModelUkmoUkDeterministic2km
	ModelUkmoSeamless
	ModelNcepGfswave016
	ModelNcepNbmConus
	ModelUkmoGlobalEnsemble20km
	ModelEcmwfAifs025Single
	ModelJmaJaxaHimawari
	ModelEumetsatSarah3
	ModelEumetsatLsaSafMsg
	ModelEumetsatLsaSafIodc
	ModelSatelliteRadiationSeamless
	ModelKmaGdps
	ModelKmaLdps
	ModelKmaSeamless
	ModelItaliaMeteoArpaeIcon2i
	ModelUkmoUkEnsemble2km
	ModelMeteofranceAromeFranceHd15min
	ModelMeteofranceAromeFrance15min
	ModelMeteoswissIconCh1
	ModelMeteoswissIconCh2
	ModelMeteoswissIconCh1Ensemble
	ModelMeteoswissIconCh2Ensemble
	ModelMeteoswissIconSeamless
	ModelNcepNamConus
	ModelIconD2Ruc
	ModelEcmwfSeas5
)

var modelNames = [...]string{
	"undefined",
	"best_match",
	"gfs_seamless",
	"gfs_global",
	"gfs_hrrr",
	"meteofrance_seamless",
	"meteofrance_arpege_seamless",
	"meteofrance_arpege_world",
	"meteofrance_arpege_europe",
	"meteofrance_arome_seamless",
	"meteofrance_arome_france",
	"meteofrance_arome_france_hd",
	"jma_seamless",
	"jma_msm",
	"jms_gsm",
	"jma_gsm",
	"gem_seamless",
	"gem_global",
	"gem_regional",
	"gem_hrdps_continental",
	"icon_seamless",
	"icon_global",
	"icon_eu",
	"icon_d2",
	"ecmwf_ifs04",
	"metno_nordic",
	"era5_seamless",
	"era5",
	"cerra",
	"era5_land",
	"ecmwf_ifs",
	"gwam",
	"ewam",
	"glofas_seamless_v3",
	"glofas_forecast_v3",
	"glofas_consolidated_v3",
	"glofas_seamless_v4",
	"glofas_forecast_v4",
	"glofas_consolidated_v4",
	"gfs025",
	"gfs05",
	"CMCC_CM2_VHR4",
	"FGOALS_f3_H_highresSST",
	"FGOALS_f3_H",
	"HiRAM_SIT_HR",
	"MRI_AGCM3_2_S",
	"EC_Earth3P_HR",
	"MPI_ESM1_2_XR",
	"NICAM16_8S",
	"cams_europe",
	"cams_global",
	"cfsv2",
	"era5_ocean",
	"cma_grapes_global",
	"bom_access_global",
	"bom_access_global_ensemble",
	"arpae_cosmo_seamless",
	"arpae_cosmo_2i",
	"arpae_cosmo_2i_ruc",
	"arpae_cosmo_5m",
	"ecmwf_ifs025",
	"ecmwf_aifs025",
	"gfs013",
	"gfs_graphcast025",
	"ecmwf_wam025",
	"meteofrance_wave",
	"meteofrance_currents",
	"ecmwf_wam025_ensemble",
	"ncep_gfswave025",
	"ncep_gefswave025",
	"knmi_seamless",
	"knmi_harmonie_arome_europe",
	"knmi_harmonie_arome_netherlands",
	"dmi_seamless",
	"dmi_harmonie_arome_europe",
	"metno_seamless",
	"era5_ensemble",
	"ecmwf_ifs_analysis",
	"ecmwf_ifs_long_window",
	"ecmwf_ifs_analysis_long_window",
	"ukmo_global_deterministic_10km",
	"ukmo_uk_deterministic_2km",
	"ukmo_seamless",
	"ncep_gfswave016",
	"ncep_nbm_conus",
	"ukmo_global_ensemble_20km",
	"ecmwf_aifs025_single",
	"jma_jaxa_himawari",
	"eumetsat_sarah3",
	"eumetsat_lsa_saf_msg",
	"eumetsat_lsa_saf_iodc",
	"satellite_radiation_seamless",
	"kma_gdps",
	"kma_ldps",
	"kma_seamless",
	"italia_meteo_arpae_icon_2i",
	"ukmo_uk_ensemble_2km",
	"meteofrance_arome_france_hd_15min",
	"meteofrance_arome_france_15min",
	"meteoswiss_icon_ch1",
	"meteoswiss_icon_ch2",
	"meteoswiss_icon_ch1_ensemble",
	"meteoswiss_icon_ch2_ensemble",
	"meteoswiss_icon_seamless",
	"ncep_nam_conus",
	"icon_d2_ruc",
	"ecmwf_seas5",
}

func (v Model) String() string {
	if i := int(v); i >= 0 && i < len(modelNames) {
		return modelNames[i]
	}
	return "Model(" + strconv.Itoa(int(v)) + ")"
}

type Variable byte

const (
	VariableUndefined Variable = iota
	VariableApparentTemperature
	VariableCape
	VariableCloudCover
	VariableCloudCoverHigh
	VariableCloudCoverLow
	VariableCloudCoverMid
	VariableDaylightDuration
	VariableDewPoint
	VariableDiffuseRadiation
	VariableDiffuseRadiationInstant
	VariableDirectNormalIrradiance
	VariableDirectNormalIrradianceInstant
	VariableDirectRadiation
	VariableDirectRadiationInstant
	VariableEt0FaoEvapotranspiration
	VariableEvapotranspiration
	VariableFreezingLevelHeight
	VariableGrowingDegreeDays
	VariableIsDay
	VariableLatentHeatFlux
	VariableLeafWetnessProbability
	VariableLiftedIndex
	VariableLightningPotential
	VariablePrecipitation
	VariablePrecipitationHours
	VariablePrecipitationProbability
	VariablePressureMsl
	VariableRain
	VariableRelativeHumidity
	VariableRunoff
	VariableSensibleHeatFlux
	VariableShortwaveRadiation
	VariableShortwaveRadiationInstant
	VariableShowers
	VariableSnowDepth
	VariableSnowHeight
	VariableSnowfall
	VariableSnowfallHeight
	VariableSnowfallWaterEquivalent
	VariableSunrise
	VariableSunset
	VariableSoilMoisture
	VariableSoilMoistureIndex
	VariableSoilTemperature
	VariableSurfacePressure
	VariableSurfaceTemperature
	VariableTemperature
	VariableTerrestrialRadiation
	VariableTerrestrialRadiationInstant
	VariableTotalColumnIntegratedWaterVapour
	VariableUpdraft
	VariableUvIndex
	VariableUvIndexClearSky
	VariableVapourPressureDeficit
	VariableVisibility
	VariableWeatherCode
	VariableWindDirection
	VariableWindGusts
	VariableWindSpeed
	VariableVerticalVelocity
	VariableGeopotentialHeight
	VariableWetBulbTemperature
	VariableRiverDischarge
	VariableWaveHeight
	VariableWavePeriod
	VariableWaveDirection
	VariableWindWaveHeight
	VariableWindWavePeriod
	VariableWindWavePeakPeriod
	VariableWindWaveDirection
	VariableSwellWaveHeight
	VariableSwellWavePeriod
	VariableSwellWavePeakPeriod
	VariableSwellWaveDirection
	VariablePm10
	VariablePm2p5
	VariableDust
	VariableAerosolOpticalDepth
	VariableCarbonMonoxide
	VariableNitrogenDioxide
	VariableAmmonia
	VariableOzone
	VariableSulphurDioxide
	VariableAlderPollen
	VariableBirchPollen
	VariableGrassPollen
	VariableMugwortPollen
	VariableOlivePollen
	VariableRagweedPollen
	VariableEuropeanAqi
	VariableEuropeanAqiPm2p5
	VariableEuropeanAqiPm10
	VariableEuropeanAqiNitrogenDioxide
	VariableEuropeanAqiOzone
	VariableEuropeanAqiSulphurDioxide
	VariableUsAqi
	VariableUsAqiPm2p5
	VariableUsAqiPm10
	VariableUsAqiNitrogenDioxide
	VariableUsAqiOzone
	VariableUsAqiSulphurDioxide
	VariableUsAqiCarbonMonoxide
	VariableSunshineDuration
	VariableConvectiveInhibition
	VariableShortwaveRadiationClearSky
	VariableGlobalTiltedIrradiance
	VariableGlobalTiltedIrradianceInstant
	VariableOceanCurrentVelocity
	VariableOceanCurrentDirection
	VariableCloudBase
	VariableCloudTop
	VariableMassDensity
	VariableBoundaryLayerHeight
	VariableFormaldehyde
	VariableGlyoxal
	VariableNonMethaneVolatileOrganicCompounds
	VariablePm10Wildfires
	VariablePeroxyacylNitrates
	VariableSecondaryInorganicAerosol
	VariableResidentialElementaryCarbon
	VariableTotalElementaryCarbon
	VariablePm25TotalOrganicMatter
	VariableSeaSaltAerosol
	VariableNitrogenMonoxide
	VariableThunderstormProbability
	VariableRainProbability
	VariableFreezingRainProbability
	VariableIcePelletsProbability
	VariableSnowfallProbability
	VariableCarbonDioxide
	VariableMethane
	VariableSeaLevelHeightMsl
	VariableSeaSurfaceTemperature
	VariableInvertBarometerHeight
	VariableHail
	VariableAlbedo
	VariablePrecipitationType
	VariableConvectiveCloudBase
	VariableConvectiveCloudTop
	VariableSnowDepthWaterEquivalent
	VariableSecondarySwellWaveHeight
	VariableSecondarySwellWavePeriod
	VariableSecondarySwellWavePeakPeriod
	VariableSecondarySwellWaveDirection
	VariableTertiarySwellWaveHeight
	VariableTertiarySwellWavePeriod
	VariableTertiarySwellWavePeakPeriod
	VariableTertiarySwellWaveDirection
	VariableWindUComponent
	VariableWindVComponent
	VariableTemperatureMax24h
	VariableTemperatureMin24h
	VariableTemperatureMean24h
	VariableSnowDensity
	VariableLongwaveRadiation
	VariableSeaIceCover
	VariableKIndex
	VariableRoughnessLength
	VariablePotentialEvapotranspiration
)

var variableNames = [...]string{
	"undefined",
	"apparent_temperature",
	"cape",
	"cloud_cover",
	"cloud_cover_high",
	"cloud_cover_low",
	"cloud_cover_mid",
	"daylight_duration",
	"dew_point",
	"diffuse_radiation",
	"diffuse_radiation_instant",
	"direct_normal_irradiance",
	"direct_normal_irradiance_instant",
	"direct_radiation",
	"direct_radiation_instant",
	"et0_fao_evapotranspiration",
	"evapotranspiration",
	"freezing_level_height",
	"growing_degree_days",
	"is_day",
	"latent_heat_flux",
	"leaf_wetness_probability",
	"lifted_index",
	"lightning_potential",
	"precipitation",
	"precipitation_hours",
	"precipitation_probability",
	"pressure_msl",
	"rain",
	"relative_humidity",
	"runoff",
	"sensible_heat_flux",
	"shortwave_radiation",
	"shortwave_radiation_instant",
	"showers",
	"snow_depth",
	"snow_height",
	"snowfall",
	"snowfall_height",
	"snowfall_water_equivalent",
	"sunrise",
	"sunset",
	"soil_moisture",
	"soil_moisture_index",
	"soil_temperature",
	"surface_pressure",
	"surface_temperature",
	"temperature",
	"terrestrial_radiation",
	"terrestrial_radiation_instant",
	"total_column_integrated_water_vapour",
	"updraft",
	"uv_index",
	"uv_index_clear_sky",
	"vapour_pressure_deficit",
	"visibility",
	"weather_code",
	"wind_direction",
	"wind_gusts",
	"wind_speed",
	"vertical_velocity",
	"geopotential_height",
	"wet_bulb_temperature",
	"river_discharge",
	"wave_height",
	"wave_period",
	"wave_direction",
	"wind_wave_height",
	"wind_wave_period",
	"wind_wave_peak_period",
	"wind_wave_direction",
	"swell_wave_height",
	"swell_wave_period",
	"swell_wave_peak_period",
	"swell_wave_direction",
	"pm10",
	"pm2p5",
	"dust",
	"aerosol_optical_depth",
	"carbon_monoxide",
	"nitrogen_dioxide",
	"ammonia",
	"ozone",
	"sulphur_dioxide",
	"alder_pollen",
	"birch_pollen",
	"grass_pollen",
	"mugwort_pollen",
	"olive_pollen",
	"ragweed_pollen",
	"european_aqi",
	"european_aqi_pm2p5",
	"european_aqi_pm10",
	"european_aqi_nitrogen_dioxide",
	"european_aqi_ozone",
	"european_aqi_sulphur_dioxide",
	"us_aqi",
	"us_aqi_pm2p5",
	"us_aqi_pm10",
	"us_aqi_nitrogen_dioxide",
	"us_aqi_ozone",
	"us_aqi_sulphur_dioxide",
	"us_aqi_carbon_monoxide",
	"sunshine_duration",
	"convective_inhibition",
	"shortwave_radiation_clear_sky",
	"global_tilted_irradiance",
	"global_tilted_irradiance_instant",
	"ocean_current_velocity",
	"ocean_current_direction",
	"cloud_base",
	"cloud_top",
	"mass_density",
	"boundary_layer_height",
	"formaldehyde",
	"glyoxal",
	"non_methane_volatile_organic_compounds",
	"pm10_wildfires",
	"peroxyacyl_nitrates",
	"secondary_inorganic_aerosol",
	"residential_elementary_carbon",
	"total_elementary_carbon",
	"pm2_5_total_organic_matter",
	"sea_salt_aerosol",
	"nitrogen_monoxide",
	"thunderstorm_probability",
	"rain_probability",
	"freezing_rain_probability",
	"ice_pellets_probability",
	"snowfall_probability",
	"carbon_dioxide",
	"methane",
	"sea_level_height_msl",
	"sea_surface_temperature",
	"invert_barometer_height",
	"hail",
	"albedo",
	"precipitation_type",
	"convective_cloud_base",
	"convective_cloud_top",
	"snow_depth_water_equivalent",
	"secondary_swell_wave_height",
	"secondary_swell_wave_period",
	"secondary_swell_wave_peak_period",
	"secondary_swell_wave_direction",
	"tertiary_swell_wave_height",
	"tertiary_swell_wave_period",
	"tertiary_swell_wave_peak_period",
	"tertiary_swell_wave_direction",
	"wind_u_component",
	"wind_v_component",
	"temperature_max24h",
	"temperature_min24h",
	"temperature_mean24h",
	"snow_density",
	"longwave_radiation",
	"sea_ice_cover",
	"k_index",
	"roughness_length",
	"potential_evapotranspiration",
}

func (v Variable) String() string {
	if i := int(v); i >= 0 && i < len(variableNames) {
		return variableNames[i]
	}
	return "Variable(" + strconv.Itoa(int(v)) + ")"
}

type Aggregation byte

const (
	AggregationNone Aggregation = iota
	AggregationMinimum
	AggregationMaximum
	AggregationMean
	AggregationP10
	AggregationP25
	AggregationMedian
	AggregationP75
	AggregationP90
	AggregationDominant
	AggregationSum
	AggregationSpread
	AggregationAnomaly
)

var aggregationNames = [...]string{
	"none",
	"minimum",
	"maximum",
	"mean",
	"p10",
	"p25",
	"median",
	"p75",
	"p90",
	"dominant",
	"sum",
	"spread",
	"anomaly",
}

func (v Aggregation) String() string {
	if i := int(v); i >= 0 && i < len(aggregationNames) {
		return aggregationNames[i]
	}
	return "Aggregation(" + strconv.Itoa(int(v)) + ")"
}
