// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	DeleteConversation(ctx context.Context, id string) error
	GetConversation(ctx context.Context, id string) (Conversation, error)
	GetMessagesByConversationId(ctx context.Context, conversationID string) ([]Message, error)
	ListConversations(ctx context.Context, arg ListConversationsParams) ([]Conversation, error)
	UpdateConversationTimestamp(ctx context.Context, id string) error
}

var _ Querier = (*Queries)(nil)
